### ISSUE TITLE
Allow starring issues

### ISSUE THREAD

**Issue by marsjaninzmarsa** [rmccue/not-trac#28]

**Comment by rmccue** [comment]
Assuming you mean for notifications?

<img width="828" alt="screenshot 2017-12-07 11 55 55" src="https://user-images.githubusercontent.com/21655/33694777-9b4dcc4a-db45-11e7-8341-f841aa13dfdb.png">

This is pretty tough to do, since the notification system a) isn't part of Trac, but is rather [part of the Make site](https://meta.trac.wordpress.org/browser/sites/trunk/wordpress.org/public_html/wp-content/plugins/trac-notifications), b) is [generated as HTML by the endpoints](https://make.wordpress.org/core/?trac-notifications=31245), and c) doesn't have cross-origin support enabled.

We'd need to change [the backend on .org](https://meta.trac.wordpress.org/browser/sites/trunk/wordpress.org/public_html/wp-content/plugins/trac-notifications/trac-notifications.php) to support these pieces. Additionally, to actually *change* your notifications, we'd need authentication (which means nonces right now).

I don't think this is really possible right now, alas.
